### ISSUE TITLE
Incorrect track being matched

### ISSUE THREAD

**Issue by returnfloat** [regisb/spotify-onthego#7]
Pafy.getbestaudio() (in youtube.py) leads to an incorrect song being downloaded when the quality of an incorrect match is higher than the correct match in the search results.
For example, look at this search - https://www.youtube.com/results?search_query=Gaia+Carnation+[Mix+Cut]+-+Original+Mix.
The correct song is 1st in the search results but Pafy.getbestaudio() chooses the 4th song in the search results leading to download of an incorrect song.
Is it possible to match parts of the title of the song returned by Pafy.getbestaudio() before downloading the song? An alternative could be downloading the first result, which based on my limited experimentation seems to be more accurate for songs which have fewer correct results in the search.

**Comment by regisb** [comment]
@returnfloat: I'm really sorry, somehow I never saw that you opened this issue. Must have been lost in my mailbox.

Does this problem still affect you? Could you please give me links to the corresponding youtube song that you wish were downloaded? (I suspect the "4th song" could be different for you and me because youtube may taylor search results to each individual user)

**Comment by regisb** [comment]
Closing this now. Please re-open if the issue still affects you.
